version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 65XR2phog-
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: denis.chernyschov2011@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: QBx6hsiDn_
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - 80:80
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: